### ISSUE TITLE
TypeError: WriteImage() got an unexpected keyword argument 'image'

### ISSUE THREAD

**Issue by j-onne** [DIAGNijmegen/rse-panimg#109]
What could cause this error? 

Traceback (most recent call last):

  Cell In[303], line 1
    result = convert(

  File C:\MyPrograms\Anaconda\Lib\site-packages\panimg\panimg.py:33 in convert
    _convert_directory(

  File C:\MyPrograms\Anaconda\Lib\site-packages\panimg\panimg.py:104 in _convert_directory
    builder_result = _build_files(

  File C:\MyPrograms\Anaconda\Lib\site-packages\panimg\panimg.py:136 in _build_files
    n_image, n_image_files = result.save(

  File C:\MyPrograms\Anaconda\Lib\site-packages\panimg\models.py:380 in save
    WriteImage(

TypeError: WriteImage() got an unexpected keyword argument 'image'

**Comment by jmsmkn** [comment]
See my previous response in #108
