### ISSUE TITLE
Improve support for Enhanced DICOM

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/rse-panimg#23]
Reading enhanced DICOM where all slices are stored in a single .dcm file does not work correctly yet. For example, the spacing between slices is not computed correctly.

**Comment by jmsmkn** [comment]
Can you provide a failing test case?

**Comment by nlessmann** [comment]
Yes, I've put a .dcm file into `/mnt/netcache/bodyct/temp/forMike`

**Comment by jmsmkn** [comment]
We really need things that can go into the test suite. Is there not something with a liberal data use license (eg CC, CC-BY) that could be included in the repo instead?

**Comment by nlessmann** [comment]
Sure, I've put a new example into that folder, derived from https://doi.org/10.5281/zenodo.4564338

**Comment by kiranvaidhya** [comment]
+1 for this issue. `panimg` fails on multiframe DICOMs (all slices stored in a single .dcm file) as @nlessmann reported in the first comment.

**Comment by jmsmkn** [comment]
This is using pydicom and panimg pure python, no web stuff, I would imagine that this is a perfect issue for a student experienced with loading DICOM images to tackle.
