### ISSUE TITLE
I got "GDCM is unavailable"

### ISSUE THREAD

**Issue by hihunjin** [DIAGNijmegen/rse-panimg#38]
from [this line of the code](https://github.com/DIAGNijmegen/rse-panimg/blob/3f213353b8b74efd88d56183d4180c9be85d17ef/panimg/image_builders/dicom.py#L365)

I got 
```console
GDCM is unavailable, conversion of DICOM with compressed transfer syntax will fail to convert. To correct this, install GDCM
```
What should I do?
I tried to do
```console
panimg convert my_dat_and_mrxs_directory output.tiff
```
How do I install ``GDCM``?

**Comment by jmsmkn** [comment]
Are you actually trying to convert "DICOM with compressed transfer syntax will fail to convert". If no, and I assume you're not as you are trying to convert dat and mxrs, then you can ignore that warnings. 

If you are, then please search on the internet for how to install it for your system.
