### ISSUE TITLE
Processing 4D MHA results in mangled TransformMatrix

### ISSUE THREAD

**Issue by chrisvanrun** [DIAGNijmegen/rse-panimg#44]
When uploading a 4D MHA file, the header `TransformMatrix` is being mangled. This results in incorrect voxel-to-world placement.

Pre-upload header:
`TransformMatrix = 0.99984952927629189 0.0019038487920032977 0.017242220441539672 0 4.97709998215079e-11 0.99395913200852193 -0.1097508264063002 0 -0.017347011442247363 0.10973431212088146 0.99380957025849759 0 0 0 0 1`

Post-upload header:
`TransformMatrix = 0.99984952927629189 4.97709998215079e-11 -0.017347011442247363 0 0.0019038487920032977 0.99395913200852193 0.10973431212088146 0 0.017242220441539672 -0.1097508264063002 0.99380957025849759 0 0 0 0 1`

# PRE (all headers)
```
ObjectType = Image
NDims = 4
BinaryData = True
BinaryDataByteOrderMSB = False
CompressedData = True
CompressedDataSize = 62117126
TransformMatrix = 0.99984952927629189 0.0019038487920032977 0.017242220441539672 0 4.97709998215079e-11 0.99395913200852193 -0.1097508264063002 0 -0.017347011442247363 0.10973431212088146 0.99380957025849759 0 0 0 0 1
Offset = -94.202199941380002 -65.439647421952998 -35.101142521466997 0
CenterOfRotation = 0 0 0 0
ElementSpacing = 0.85714286565780995 0.85714286565780995 2.9999999999999916 1
DimSize = 224 224 26 45
AnatomicalOrientation = ????
ElementType = MET_USHORT
ElementDataFile = LOCAL
```

# Post (all header)
```
Postprocessed
ObjectType = Image
NDims = 4
BinaryData = True
BinaryDataByteOrderMSB = False
CompressedData = True
CompressedDataSize = 62117126
TransformMatrix = 0.99984952927629189 4.97709998215079e-11 -0.017347011442247363 0 0.0019038487920032977 0.99395913200852193 0.10973431212088146 0 0.017242220441539672 -0.1097508264063002 0.99380957025849759 0 0 0 0 1
Offset = -94.202199941380002 -65.439647421952998 -35.101142521466997 0
CenterOfRotation = 0 0 0 0
ElementSpacing = 0.85714286565780995 0.85714286565780995 2.9999999999999916 1
DimSize = 224 224 26 45
AnatomicalOrientation = ????
ElementType = MET_USHORT
ElementDataFile = LOCAL
```

**Comment by chrisvanrun** [comment]
@henkjanhuisman , @MatinHz , @anindox8 this is causing the issue for the prostate MRI

**Comment by jmsmkn** [comment]
The output matrix is the pseudo-inverse of the input.

I do not recall that we mess around with those, and if this is mha -> mha then they should be untouched. However, for 4D this method is used to construct the volumes, and this is using `SetDirection` when extracting information from the input header: https://github.com/DIAGNijmegen/rse-panimg/blob/2b37e8599d646fbb2ca531af65e6700bb81c0750/panimg/image_builders/metaio_utils.py#L179. I'm not sure what the API on that call is. There is a better way to copy over the image information using `output_sitk_img.CopyInformation(input_sitk_img)`, but I'm not sure why there image is not read at that point, I remember there being problems with 4D data but this code was provided by the 4DCT group, so maybe it is an issue there too? It might be simply an ordering issue, simpleITK sets spacing, then origin, then direction. 

For 1D, 2D and 3D the operation is straightforward so the problem shouldn't appear there: https://github.com/DIAGNijmegen/rse-panimg/blob/2b37e8599d646fbb2ca531af65e6700bb81c0750/panimg/image_builders/metaio_utils.py#L303

**Comment by pkcakeout** [comment]
Just was looking this up myself :D  Thanks James, you were faster. It would probably help to get access to the original data. One thing I notice, when comparing the matrices is that one matrix component seems to be _mirrored_:

~~~~~~
One matrix
[[ 1.    0.    0.02  0.  ]
 [ 0.    0.99 -0.11  0.  ]
 [-0.02  0.11  0.99  0.  ]
 [ 0.    0.    0.    1.  ]]
Other matrix
[[ 1.    0.   -0.02  0.  ]
 [ 0.    0.99  0.11  0.  ]
 [ 0.02 -0.11  0.99  0.  ]
 [ 0.    0.    0.    1.  ]]
One - Other matrix
[[ 0.    0.    0.03  0.  ]
 [-0.    0.   -0.22  0.  ]
 [-0.03  0.22  0.    0.  ]
 [ 0.    0.    0.    0.  ]]
~~~~~~

Maybe that is the root of the issue or helps with debugging what is going on?

**Comment by jmsmkn** [comment]
It's pseudo inverse (e.g. `out = numpy.linalg.pinv(input_matrix)`), you can check it with numpy.

**Comment by jmsmkn** [comment]
Correction, it's just the inverse, my linear algebra is rusty...

```
import numpy
input = numpy.array([[ 0.99984952927629189,   0.0019038487920032977 ,  0.017242220441539672, 0 ],
[ 4.97709998215079e-11,  0.99395913200852193  , -0.1097508264063002   , 0 ],
[-0.017347011442247363,  0.10973431212088146  ,  0.99380957025849759 ,  0 ],
[0, 0, 0, 1]])
output = numpy.array([[ 0.99984952927629189,   4.97709998215079e-11,  -0.017347011442247363,  0 ],
[ 0.0019038487920032977, 0.99395913200852193,    0.10973431212088146,   0 ],
[ 0.017242220441539672, -0.1097508264063002,     0.99380957025849759,   0 ],
[0, 0, 0, 1]])

print(numpy.allclose(output,numpy.linalg.inv(input)))
print(output - numpy.linalg.inv(input))
```

```
True
[[ 0.00000000e+00  7.65671785e-20 -3.46944695e-18  0.00000000e+00]
 [ 2.16840434e-19  1.11022302e-16  2.77555756e-17  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
```

**Comment by chrisvanrun** [comment]
FYI, a small update.

I think it's the transpose. Looking at the diagonal decimal signature, it fits better than the inverse does.

I am slowly pin-pointing they why and how, complicated by strange intermediate states (unfortunately being used within tests).

For some matrices, say matrix `A`, the following happens correctly for the full SimpleITK route:

- SimpleITK **reading**  transposes the header matrix A:
`transpose(A)` -> `Direction`. 
- [...] do stuff
- SimpleITK **writing** does another transpose on the Direction: 
`transpose(Direction)` -> `transpose(transpose(A))` -> `A`.

Whereas the custom code `load_sitk_image_with_nd_support()` does the following incorrectly:

- **Read** matrix `A` as `Direction`
- [...] do stuff
- Uses SimpleITK to **write**:
`transpose(Direction)` -> `transpose(A)`

Time to dive into the C-source code of (Simple)ITK ... to be continued

**Comment by chrisvanrun** [comment]
Minimal reproduction code: possibly a double bug in ITK. To be continued.

```

import SimpleITK as sitk
img = sitk.Image([10]*4,sitk.sitkFloat32)
img.SetDirection([0.9998495292762919, 0.0019038487920032977, 0.017242220441539672, 0.0, 4.97709998215079e-11, 0.9939591320085219, -0.1097508264063002, 0.0, -0.017347011442247363, 0.10973431212088146, 0.9938095702584976, 0.0, 0.0, 0.0, 0.0, 1.0]
)
sitk.WriteImage(img, "test.mhd")
with open("test.mhd", "r") as f:
    while True:
        line = f.readline()
        if not line:
            break
        line = line.rstrip()
        if "TransformMatrix" in line:
            file_matrix = tuple(line.split(" = ")[1].split(" "))

reader = sitk.ImageFileReader()
reader.SetFileName("test.nrrd")
reader.ReadImageInformation()
print(img.GetDirection())  # (0.9998495292762919, 0.0019038487920032977, 0.017242220441539672, [..]
print(reader.GetDirection()) #  (0.9998495292762919, 0.0019038487920032977, 0.017242220441539672, [..]
print(file_matrix)  # ('0.99984952927629189', '4.97709998215079e-11', '-0.017347011442247363',  [..]
```

**Comment by chrisvanrun** [comment]
Yep, format confusion.

`SimpleITK.SetDirection()` expects the input to be a in [row-major format](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1Image.html#a7bd35f108a2df5c966285405af409548). 

In contrast, SimpleITK seems to write it in [column-major format](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/Code/IO/src/sitkImageFileReader.cxx#L145-L149) to file. 

Quick Python sanity check of the later:
```
o_tm = (1.0, 0.0, 0.02, 0.0, 0.0, 0.99, -0.11, 0.0, -0.02, 0.11, 0.98, 0.0, 0.0, 0.0, 0.0, 1.0)
a = np.array(o_tm).reshape(4,4)
tm = []
for i in range(0,4):
  for col in range(0,4):
    tm.append(a[col][i])
print(o_tm)  # (1.0, 0.0, 0.02, 0.0, 0.0, 0.99, -0.11, 0.0, -0.02, 0.11, 0.98, 0.0, 0.0, 0.0, 0.0, 1.0)
print(tm)  # [1.0, 0.0, -0.02, 0.0, 0.0, 0.99, 0.11, 0.0, 0.02, -0.11, 0.98, 0.0, 0.0, 0.0, 0.0, 1.0]
```

So, the actual header content is in column-major format and was incorrectly passed in that format to the `SetDirection()` in the original setting. This would also happen for 3D images, but the method was exclusively followed for 4+D images. 

If leaving the original route it could have been fixed by column -> row formatting the original `TransformMatrix`.

# Impact assessment
All previous 4D images would have been incorrectly positioned in world space, including any made annotations. Unless they utilised an identity matrix as `TransformMatrix`.
