### ISSUE TITLE
Error when window center and width are arrays in MHA

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/rse-panimg#5]
eg `WindowCenter = [60, 60]`, same for window width. This is perfectly valid, so should be accepted.

See https://github.com/comic/grand-challenge.org/issues/1376

**Comment by jmsmkn** [comment]
@chrisvanrun Would you be able to fix this?

**Comment by pkcakeout** [comment]
Hey James! Quick important, nitpicky questions: Are you sure that this is _valid dicom_? I also am a bit confused about what it would mean? 

For reference: https://dicom.innolitics.com/ciods/ct-image/voi-lut/00281051 and (org source) http://dicom.nema.org/medical/dicom/current/output/pdf/part06.pdf The Dicom standard lists the window-data to be single DS types (Decimal Strings), which are defined here: http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html and may only contain:

~~~~~~
"0"-"9", "+", "-", "E", "e", "." of Default Character Repertoire
~~~~~~

So no brackets etc.

I found _some_ hints for what multiple WindowWidths and centers _could_ mean in "C.11.2.1.2.2 General Requirements for Window Center and Window Width" from this page: https://dicom.innolitics.com/ciods/ct-image/voi-lut/00281056. It indicates that multiple window-values will be paired up an represent multiple possible views for a given image.

So my main question for "solidifying" this would be:
- Is the actual DICOM string "[60, 60]" or is that just the Python-view of that data?
    - First case would point towards invalid DICOM - how much of that would we want to support of that?
- If this is the case of multiple-DICOM window levels, I assume it is fine to only read the first value? Trying to determine the actual solution here. Or do we need multi-windowlevel support in CIRRUS as well?

**Comment by jmsmkn** [comment]
Yes - see https://dicom.innolitics.com/ciods/ct-image/voi-lut/00281051, it has a value multiplicity of 1-n. From the spec there

> If multiple values are present, both Attributes shall have the same number of values and shall be considered as pairs. Multiple values indicate that multiple alternative views should be presented.

These are represented as arrays in pydicom, and so added to mha like this. Maybe the bug is from mha writing in the first place, but this is what you get when taking the naive approach so we should expect this from any mha that a user has created outside of panimg. I don't know what the extent of the support in ITK is.

For CIRRUS it's another issue about what we want to support. It's "should be presented", not "must". There are already a lot of mha in the datastore with WindowCenter and WindowWidth in this format, and CIRRUS copes ok with it right now.

**Comment by jmsmkn** [comment]
IMO: This is valid DICOM and more of a decision about what we want to support in MHA files. ITK doesn't seem to say anything about WindowCenter and WindowWidth representations. I would say we want to support these values being numbers or arrays of equal length in the MHA we ingest.

**Comment by pkcakeout** [comment]
`has a value multiplicity of 1-n`... ah, yes. That means repeated tags, right? I think that I remember. 

Anyway, easiest way to clone (parts of) the DICOM dictionary is the way I did it for Oncology, I would say, which is to extract it as a parsed (thus normalized) JSON structure. Works really well. Not DICOM-madness left afterwards. Anyway, this is not what this issue is about. Thanks for pointing out the multiplicity! I think that makes it easier for a "DICOM-beginner" to work with this. The DICOM data dictionary is not always easy to traverse so I wanted to make sure that we are all on the same page :)
