### ISSUE TITLE
`nifti` and `nrrd` readers are not doing any header validation

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/rse-panimg#6]
See https://github.com/comic/grand-challenge.org/issues/1376#issuecomment-747460066

**Comment by nlessmann** [comment]
This issue seems to be resolved, at least I haven't come across this problem anymore for a while.

I noticed though that the nifti and nrrd readers are not doing any header validation at the moment, so the issue of having that not harmonized across different builders remains.
