### ISSUE TITLE
Naming of cases imported as dicom files

### ISSUE THREAD

**Issue by EwoudSmit** [DIAGNijmegen/rse-panimg#63]
Currently, imported dicom files are named after the studyUID (more precise: [studyUID-0]).

When uploading two series of the same study (e.g. CT Chest and CT abdomen), these series get the same name. As the hanging list of the reader study requires unique names, I cannot add both series in my reader study.

For clarity, the hierarchical levels of dicom are: patient, study, series, image. Now, series seem to be named after the study.

A potential solution is to name the dicom files after the seriesUID instead of the studyUID (I assume we generally review series in GC not whole studies). Alternatively, if the name could for example be numbered by adding the series number e.g. [studyUID-seriesnumber] (if you like to group images of the same study by name).

**Comment by jmsmkn** [comment]
> Alternatively, if the name could for example be numbered by adding the series number e.g. [studyUID-seriesnumber]

This is already what is done. If you want to differentiate them then upload them in the same upload session. Or, convert them offline, name them what you like and upload the mhas.
